name: shop_flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#8E6CEF"
  android_12:
    color: "#8E6CEF"
    image: "assets/images/splash.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gabarito
      fonts:
        - asset: assets/fonts/Gabarito/static/Gabarito-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  field_prefix: null
